### ISSUE TITLE
failed to access the OpenAI API: invalid_request_error

### ISSUE THREAD

**Issue by niumanniu** [sqlchat/sqlchat#10]
[root@rdsdev sqlchat]# pnpm dev

> sqlchat@ dev /home/app/sqlchat
> next dev

warn  - Port 3000 is in use, trying 3001 instead.
ready - started server on 0.0.0.0:3001, url: http://localhost:3001
info  - Loaded env from /home/app/sqlchat/.env
event - compiled client and server successfully in 6.7s (184 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 1863 ms (185 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
wait  - compiling / (client and server)...
event - compiled client and server successfully in 3s (2906 modules)
wait  - compiling /api/chat (client and server)...
event - compiled successfully in 514 ms (66 modules)

error - pages/api/chat.ts (11:23) @ fetch
error - fetch failed
   9 | const handler = async (req: NextRequest) => {
  10 |   const reqBody = await req.json();
> 11 |   const rawRes = await fetch(`https://api.openai.com/v1/chat/completions`, {
     |                       ^
  12 |     headers: {
  13 |       "Content-Type": "application/json",
  14 |       Authorization: `Bearer ${openAIApiKey}`,

**Comment by boojack** [comment]
Please check your network environment to see if you can access the OpenAI API.

**Comment by niumanniu** [comment]
curl success！ping not success！

[root@rdsdev ~]# curl https://api.openai.com/v1/chat/completions
{
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}
[root@rdsdev ~]# 
[root@rdsdev ~]# ping api.openai.com
PING api.openai.com (108.160.169.181) 56(84) bytes of data.

**Comment by niumanniu** [comment]
> Please check your network environment to see if you can access the OpenAI API.
> 
> ```shell
> ping api.openai.com
> ```

curl success！ping not success！

[root@rdsdev ~]# curl https://api.openai.com/v1/chat/completions
{
"error": {
"message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
"type": "invalid_request_error",
"param": null,
"code": null
}
}
[root@rdsdev ~]#
[root@rdsdev ~]# ping api.openai.com
PING api.openai.com (108.160.169.181) 56(84) bytes of data.


[root@rdsdev ~]# node -v
v17.2.0
[root@rdsdev ~]# pnpm -v
6.11.0

**Comment by LokiChaos970** [comment]
How do I manage to do that?

**Comment by boojack** [comment]
We have provided configuring the OpenAI API key and endpoint in the settings dialog. Please configure your OpenAI configuration and try it again.

<img width="530" alt="image" src="https://user-images.githubusercontent.com/24653555/230548923-e1242ff8-849b-4d11-baba-bd2e9b3835cb.png">

**Comment by fxgeoffrey** [comment]
I have same issue, and tried to clear all data in the setting dialog. Issue still there. 
<img width="495" alt="image" src="https://user-images.githubusercontent.com/128350100/230703781-65901255-b61f-4a3c-bae2-a220e38d055f.png">

**Comment by fxgeoffrey** [comment]
> I have same issue, and tried to clear all data in the setting dialog. Issue still there. <img alt="image" width="495" src="https://user-images.githubusercontent.com/128350100/230703781-65901255-b61f-4a3c-bae2-a220e38d055f.png">

Also use postman to check if my network problem. But it seems not.
<img width="840" alt="image" src="https://user-images.githubusercontent.com/128350100/230703927-417ad57f-29bd-4770-950f-368a286f3984.png">

**Comment by topperCao** [comment]
@fxgeoffrey 遇到一样的问题，.env里，还有前端界面设置里，都换成了自己的key，也还是不行，然后确定终端里是可以科学上网的！

**Comment by hereTac** [comment]
Check if your chat gpt api key had expired for free trail $18. https://platform.openai.com/account/usage

**Comment by oushu1tangxiangyue1** [comment]
同样的问题，科学上网正常，node中无法请求。怀疑是next框架层面的原因
