### ISSUE TITLE
MAX_TOKEN needs to be parameterized to support various models

### ISSUE THREAD

**Issue by G-Hung** [sqlchat/sqlchat#115]
### Describe the bug

https://github.com/sqlchat/sqlchat/blob/main/src/components/ConversationView/index.tsx#L26-L28
Currently, the MAX_TOKEN is hardcoded as 4000, which is almost the context limit of gpt-3.5-turbo [4096]

However, GPT4 can support 8192 tokens, which is double the MAX_TOKEN, the app can handle larger context in GPT4 if MAX_TOKEN is adjusted accordingly

reference: https://platform.openai.com/docs/models/overview

### To reproduce

As above

**Comment by tianzhou** [comment]
Fixed in https://github.com/sqlchat/sqlchat/commit/088f0904c068907c0761a7cf606b6c5a7c484dcf
