### ISSUE TITLE
can not upload file, chat

### ISSUE THREAD

**Issue by Linus6666** [sqlchat/sqlchat#124]
### Describe the bug

<img width="946" alt="2b5cd86f943a5625929ec5cd0b00f64" src="https://github.com/sqlchat/sqlchat/assets/134575458/4a18bda9-d493-48c4-adb9-53853a57a95e">
![image](https://github.com/sqlchat/sqlchat/assets/134575458/2eb59ca4-4efe-4f9f-914e-bc65c1193d94)

### To reproduce

none

### Additional context

can log in but can not upload file and do chat, is there something wrong with my setting?

**Comment by tianzhou** [comment]
The screenshot is not our sqlchat.ai product.  SQL Chat does not have upload file feature.
