### ISSUE TITLE
another way to convert natural language to sql

### ISSUE THREAD

**Issue by nobodxbodon** [sqlchat/sqlchat#133]
### Is your feature request related to a problem?

If one doesn't have openAI account or tired of quota issue.

### Describe the solution you'd like

Here's [another solution](https://github.com/nobodxbodon/rply/blob/5aabd499bcdf7d5f6edfec67cb8955c0c32b459d/tests/test_%E6%8C%89%E8%AF%AD%E6%B3%95%E5%88%86%E8%AF%8D.py#L496):
```
获取出生年大于2000的读者的邮箱、昵称，按出生年倒序排列。
=> SELECT 邮箱, 昵称 FROM 读者 WHERE 出生年 > 2000 ORDER BY 出生年 DESC;

添加读者记录，邮箱为“test@example.com”，出生年为2000。
=> INSERT INTO 读者 (邮箱, 出生年) VALUES ("test@example.com", 2000);
```
Details please see [here](https://zhuanlan.zhihu.com/p/415732605)。

**Comment by tianzhou** [comment]
Out of scope
