### ISSUE TITLE
Postgres non-default (public) schema is not supported

### ISSUE THREAD

**Issue by tea-artist** [sqlchat/sqlchat#138]
### Describe the bug

When you select a non-default schema in Postgres,  100% wrong table name will be provided.

### To reproduce

1. select a non-default Postgres schema
2. start to chat

the wrong answer
<img width="1028" alt="image" src="https://github.com/sqlchat/sqlchat/assets/113977203/4057701b-5f87-43c7-8ab1-1a2f1bf5cd72">

the correct answer should be
```sql
SELECT * FROM "bseHkg2lxx5GN"."visual_Newtable_tblsL6zOsTW115ErShz";
```

**Comment by tianzhou** [comment]
Fixed in https://github.com/sqlchat/sqlchat/commit/f2cc5e8076bf94c9b9ddb0897d4b45ca4aa94157
