### ISSUE TITLE
Cant use my own Api key 

### ISSUE THREAD

**Issue by sotiriss** [sqlchat/sqlchat#139]
### Describe the bug

![image](https://github.com/sqlchat/sqlchat/assets/44936828/f76ba90c-a585-4cd4-9f42-d0bc688614ab)

### To reproduce

docker run --name sqlchat --platform linux/amd64 --env OPENAI_API_KEY=MYKEY-p 3000:3000 sqlchat/sqlchat

### Additional context

hello i am trying to deploy Self-host with Docker i put my api key in parameteres but I got this error:  Please sign up to get free quota or supply your own OpenAI key.

**Comment by tianzhou** [comment]
Fixed https://github.com/sqlchat/sqlchat/commit/42bad976a4bd4d9b16a62bb8813555b55e6ffd1b
