### ISSUE TITLE
Please sign up to get free quota.

### ISSUE THREAD

**Issue by elgerm** [sqlchat/sqlchat#141]
### Describe the bug

Not sure if this is a configuration issue but seems like a bug. Using hosted docker to run and added my own API key from openai. 
Connection to my database works, but then when I ask anything I only get 'Please sign up to get free quota'.

### To reproduce

docker compose file:

version: '3.7'
services:
  sqlchat:
    hostname: localhost
    image: sqlchat/sqlchat:latest
    environment:
      NEXTAUTH_SECRET: 'secret'
      NEXT_PUBLIC_USE_DATABASE: 'true'
      NEXT_PUBLIC_DATABASE_URL: 'postgresql://***'
      OPENAI_API_KEY: '***'
      NEXT_PUBLIC_ALLOW_SELF_OPENAI_KEY: 'true'
    networks:
     - ***
    logging:
      driver: json-file
      options:
        max-size: 3m
    ports:
     - 3000:3000
    restart: on-failure

networks:
  ***:
    external: true
    name: ***

**Comment by tianzhou** [comment]
This is expected.

Your setting is similar to sqlchat.ai, which offers a hosted service for end users. It requires the user to log in to use the `OPENAI_API_KEY` you set in the config.

If you only intend to use for yourself. You only need to supply

NEXTAUTH_SECRET: 'secret'
OPENAI_API_KEY: 'xxx'

See README https://github.com/sqlchat/sqlchat?tab=readme-ov-file#docker for details.

**Comment by elgerm** [comment]
Hi,

Thanks but, I did specify my api key.
In my example above I put 3 stars everywhere I wanted to hide my info but markdown removed it, making it look like I didn't configure the api key (which I did). 

Elger

**Comment by tianzhou** [comment]
Because you provide the database as well, which implies running a hosted service for others to use. Because the database is used to store the account and usage information.

When you visit the running SQL Chat, you act as an end user consuming the SQL Chat, thus quota logic is enforced.

As mentioned in the previous comment. You **Only** need to supply:

NEXTAUTH_SECRET: 'secret'
OPENAI_API_KEY: 'xxx'

**Comment by Kiran967868** [comment]
I have also facing that above issue
the "sign up to get free quota"  response not solve even carefully follow all your suggestion of above,
now what can i do to solve that

**Comment by zthafir** [comment]
I'm trying to run the project locally and I already added the following environment variables:

NEXTAUTH_SECRET=secret
OPENAI_API_KEY=xxx

However, when I send any message, I get the error: "Please sign up to get free quota."
Does anyone know what might be causing this or how to fix it?
