### ISSUE TITLE
Include views in schema 

### ISSUE THREAD

**Issue by ullgren** [sqlchat/sqlchat#152]
### Is your feature request related to a problem?

Only tables in a postgresql schema is listed. The result is that views are not added into the chat context.

### Describe the solution you'd like

Detect available views in the schema and list them among the tables.
No special treatment should be necessary.

**Comment by tianzhou** [comment]
https://github.com/sqlchat/sqlchat/commit/0fe1f41086ac780f7fca962d5480301a58cc2c64
