### ISSUE TITLE
Failed to request message, please check your network.

### ISSUE THREAD

**Issue by Hec-gitHub** [sqlchat/sqlchat#159]
### Is your feature request related to a problem?

Background:
1. Using a Linux virtual machine, deploy the SQL Chat project locally and the project starts normally.
2. The correct Open AI Key value has been set.
3. In the http://xxx.xxx.xxx.xxx:3000/ The following error occurred during the conversation on the page:
**Failed to request message, please check your network.**
In the/sqlchat/src/utils/openai.ts file, the API endpoint (OPENAI-API-ENDPoint) information was checked,
The endpoint information can be accessed normally on the Windows local network.
But when accessing it on the virtual machine, the following error occurred:
`error - src/pages/api/chat.ts (107:26) @ fetch
error - fetch failed
  105 |   const apiEndpoint = getApiEndpoint(req.headers.get("x-openai-endpoint") || openAIApiEndpoint);
  106 |   const model = getModel(req.headers.get("x-openai-model") || "");
> 107 |   const remoteRes = await fetch(apiEndpoint, {
      |                          ^
  108 |     headers: headers,
  109 |     method: "POST",
  110 |     body: JSON.stringify({`

### Describe the solution you'd like

1.Can the request proxy address for open AI be specified in the project?
How to do it so that when the project sends an Open AI request, it can go through the designated agent in the project.
2. If open AI request proxies cannot be set in the project, can virtual machine network proxies be used?

### Additional context

![image](https://github.com/sqlchat/sqlchat/assets/49053243/a5575a8c-d45a-4e4b-845f-0ede13075541)

**Comment by tianzhou** [comment]
You can set the API Endpoint by specifying OPENAI_API_ENDPOINT

https://github.com/sqlchat/sqlchat?tab=readme-ov-file#openai-related
