### ISSUE TITLE
where and how to used my db schema?

### ISSUE THREAD

**Issue by xunyicjq** [sqlchat/sqlchat#22]
Do I need to provide custom DB information to the project？And how to used?

**Comment by boojack** [comment]
@xunyicjq You can add a new connection to your database instance. SQL Chat will then fetch its schema and use it in the chat context.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/24653555/231049397-5cda891d-0240-4f2b-a897-a449fe6ac2e2.png">
