### ISSUE TITLE
Token Limitation

### ISSUE THREAD

**Issue by abraham-cj** [sqlchat/sqlchat#41]
### Is your feature request related to a problem?

For some complex tables, the structure information of the table exceeds the token limit, the conversation could not proceed and gpt continuously returns incorrect and incomplete content. What are the solutions to this problem?

### Describe the solution you'd like

Solve the token limitation problem.

**Comment by tianzhou** [comment]
We now provide uses to selectively choose the table.

We don't have near term plan to workaround the token limit with the hope that the limit will be increased significantly as the model matures.
