### ISSUE TITLE
system versioned tables in mariadb not recognized

### ISSUE THREAD

**Issue by clarity99** [sqlchat/sqlchat#48]
### Describe the bug

I have a schema where some tables have SYSTEM VERSION turned on - sqlchat seems to not see these tables at all. When I ask him to show schema it shows just the tables without versioning. 

### To reproduce

CREATE TABLE test (
  id INT PRIMARY KEY,
  name VARCHAR(50),
  age INT,
  salary DECIMAL(10,2),
  period_start DATE,
  period_end DATE
  
) WITH SYSTEM VERSIONING;

create new chat window, ask to describe schema

**Comment by clarity99** [comment]
ok, so this is weird - when I run it in Safari it doesn't show versioned table, but in Brave it does. ? i thought all of this is done server side, why should browser be involved?

**Comment by tianzhou** [comment]
Fixed in https://github.com/sqlchat/sqlchat/commit/4031d3fc8447cfca11161d79321fc9cc29cd48ac

**Comment by tianzhou** [comment]
@clarity99 it's all in server side. Please pull the latest build and check again
