### ISSUE TITLE
crash when displaying output from select query

### ISSUE THREAD

**Issue by clarity99** [sqlchat/sqlchat#49]
### Describe the bug

When I try to retrieve any data from my booking table I get an error on screen:
Application error: a client-side exception has occurred (see the browser console for more information).

in console there's a bunch of errors:
framework-281bd828f4ecdac7.js:9 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20data%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lJ (framework-281bd828f4ecdac7.js:9:54221)
    at o (framework-281bd828f4ecdac7.js:9:59251)
    at uu (framework-281bd828f4ecdac7.js:9:71132)
    at i (framework-281bd828f4ecdac7.js:9:121294)
    at oO (framework-281bd828f4ecdac7.js:9:99114)
    at framework-281bd828f4ecdac7.js:9:98981
    at oF (framework-281bd828f4ecdac7.js:9:98988)
    at ox (framework-281bd828f4ecdac7.js:9:95740)
    at oS (framework-281bd828f4ecdac7.js:9:94295)
    at x (framework-281bd828f4ecdac7.js:33:1373)
a6 @ framework-281bd828f4ecdac7.js:9
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
main-b471d74b2885b119.js:1 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20data%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lJ (framework-281bd828f4ecdac7.js:9:54221)
    at o (framework-281bd828f4ecdac7.js:9:59251)
    at uu (framework-281bd828f4ecdac7.js:9:71132)
    at i (framework-281bd828f4ecdac7.js:9:121294)
    at oO (framework-281bd828f4ecdac7.js:9:99114)
    at framework-281bd828f4ecdac7.js:9:98981
    at oF (framework-281bd828f4ecdac7.js:9:98988)
    at ox (framework-281bd828f4ecdac7.js:9:95740)
    at oS (framework-281bd828f4ecdac7.js:9:94295)
    at x (framework-281bd828f4ecdac7.js:33:1373)
K @ main-b471d74b2885b119.js:1
fn @ main-b471d74b2885b119.js:1
componentDidCatch @ main-b471d74b2885b119.js:1
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
main-b471d74b2885b119.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
K @ main-b471d74b2885b119.js:1
fn @ main-b471d74b2885b119.js:1
componentDidCatch @ main-b471d74b2885b119.js:1
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
framework-281bd828f4ecdac7.js:9 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20data%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lJ (framework-281bd828f4ecdac7.js:9:54221)
    at o (framework-281bd828f4ecdac7.js:9:59251)
    at uu (framework-281bd828f4ecdac7.js:9:71132)
    at i (framework-281bd828f4ecdac7.js:9:121294)
    at oO (framework-281bd828f4ecdac7.js:9:99114)
    at framework-281bd828f4ecdac7.js:9:98981
    at oF (framework-281bd828f4ecdac7.js:9:98988)
    at ox (framework-281bd828f4ecdac7.js:9:95740)
    at oS (framework-281bd828f4ecdac7.js:9:94295)
    at x (framework-281bd828f4ecdac7.js:33:1373)
a6 @ framework-281bd828f4ecdac7.js:9
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
main-b471d74b2885b119.js:1 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20data%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lJ (framework-281bd828f4ecdac7.js:9:54221)
    at o (framework-281bd828f4ecdac7.js:9:59251)
    at uu (framework-281bd828f4ecdac7.js:9:71132)
    at i (framework-281bd828f4ecdac7.js:9:121294)
    at oO (framework-281bd828f4ecdac7.js:9:99114)
    at framework-281bd828f4ecdac7.js:9:98981
    at oF (framework-281bd828f4ecdac7.js:9:98988)
    at ox (framework-281bd828f4ecdac7.js:9:95740)
    at oS (framework-281bd828f4ecdac7.js:9:94295)
    at x (framework-281bd828f4ecdac7.js:33:1373)
K @ main-b471d74b2885b119.js:1
fn @ main-b471d74b2885b119.js:1
componentDidCatch @ main-b471d74b2885b119.js:1
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
main-b471d74b2885b119.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
K @ main-b471d74b2885b119.js:1
fn @ main-b471d74b2885b119.js:1
componentDidCatch @ main-b471d74b2885b119.js:1
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
framework-281bd828f4ecdac7.js:9 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20data%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lJ (framework-281bd828f4ecdac7.js:9:54221)
    at o (framework-281bd828f4ecdac7.js:9:59251)
    at uu (framework-281bd828f4ecdac7.js:9:71132)
    at i (framework-281bd828f4ecdac7.js:9:121294)
    at oO (framework-281bd828f4ecdac7.js:9:99114)
    at framework-281bd828f4ecdac7.js:9:98981
    at oF (framework-281bd828f4ecdac7.js:9:98988)
    at ox (framework-281bd828f4ecdac7.js:9:95740)
    at oS (framework-281bd828f4ecdac7.js:9:94295)
    at x (framework-281bd828f4ecdac7.js:33:1373)
a6 @ framework-281bd828f4ecdac7.js:9
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
main-b471d74b2885b119.js:1 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20data%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lJ (framework-281bd828f4ecdac7.js:9:54221)
    at o (framework-281bd828f4ecdac7.js:9:59251)
    at uu (framework-281bd828f4ecdac7.js:9:71132)
    at i (framework-281bd828f4ecdac7.js:9:121294)
    at oO (framework-281bd828f4ecdac7.js:9:99114)
    at framework-281bd828f4ecdac7.js:9:98981
    at oF (framework-281bd828f4ecdac7.js:9:98988)
    at ox (framework-281bd828f4ecdac7.js:9:95740)
    at oS (framework-281bd828f4ecdac7.js:9:94295)
    at x (framework-281bd828f4ecdac7.js:33:1373)
K @ main-b471d74b2885b119.js:1
fn @ main-b471d74b2885b119.js:1
componentDidCatch @ main-b471d74b2885b119.js:1
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
main-b471d74b2885b119.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
K @ main-b471d74b2885b119.js:1
fn @ main-b471d74b2885b119.js:1
componentDidCatch @ main-b471d74b2885b119.js:1
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
framework-281bd828f4ecdac7.js:9 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20data%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lJ (framework-281bd828f4ecdac7.js:9:54221)
    at o (framework-281bd828f4ecdac7.js:9:59251)
    at uu (framework-281bd828f4ecdac7.js:9:71132)
    at i (framework-281bd828f4ecdac7.js:9:121294)
    at oO (framework-281bd828f4ecdac7.js:9:99114)
    at framework-281bd828f4ecdac7.js:9:98981
    at oF (framework-281bd828f4ecdac7.js:9:98988)
    at ox (framework-281bd828f4ecdac7.js:9:95740)
    at oS (framework-281bd828f4ecdac7.js:9:94295)
    at x (framework-281bd828f4ecdac7.js:33:1373)
a6 @ framework-281bd828f4ecdac7.js:9
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
main-b471d74b2885b119.js:1 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20data%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lJ (framework-281bd828f4ecdac7.js:9:54221)
    at o (framework-281bd828f4ecdac7.js:9:59251)
    at uu (framework-281bd828f4ecdac7.js:9:71132)
    at i (framework-281bd828f4ecdac7.js:9:121294)
    at oO (framework-281bd828f4ecdac7.js:9:99114)
    at framework-281bd828f4ecdac7.js:9:98981
    at oF (framework-281bd828f4ecdac7.js:9:98988)
    at ox (framework-281bd828f4ecdac7.js:9:95740)
    at oS (framework-281bd828f4ecdac7.js:9:94295)
    at x (framework-281bd828f4ecdac7.js:33:1373)
K @ main-b471d74b2885b119.js:1
fn @ main-b471d74b2885b119.js:1
componentDidCatch @ main-b471d74b2885b119.js:1
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
main-b471d74b2885b119.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
K @ main-b471d74b2885b119.js:1
fn @ main-b471d74b2885b119.js:1
componentDidCatch @ main-b471d74b2885b119.js:1
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
framework-281bd828f4ecdac7.js:9 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20data%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lJ (framework-281bd828f4ecdac7.js:9:54221)
    at o (framework-281bd828f4ecdac7.js:9:59251)
    at uu (framework-281bd828f4ecdac7.js:9:71132)
    at i (framework-281bd828f4ecdac7.js:9:121294)
    at oO (framework-281bd828f4ecdac7.js:9:99114)
    at framework-281bd828f4ecdac7.js:9:98981
    at oF (framework-281bd828f4ecdac7.js:9:98988)
    at ox (framework-281bd828f4ecdac7.js:9:95740)
    at oS (framework-281bd828f4ecdac7.js:9:94295)
    at x (framework-281bd828f4ecdac7.js:33:1373)
a6 @ framework-281bd828f4ecdac7.js:9
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
main-b471d74b2885b119.js:1 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20data%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lJ (framework-281bd828f4ecdac7.js:9:54221)
    at o (framework-281bd828f4ecdac7.js:9:59251)
    at uu (framework-281bd828f4ecdac7.js:9:71132)
    at i (framework-281bd828f4ecdac7.js:9:121294)
    at oO (framework-281bd828f4ecdac7.js:9:99114)
    at framework-281bd828f4ecdac7.js:9:98981
    at oF (framework-281bd828f4ecdac7.js:9:98988)
    at ox (framework-281bd828f4ecdac7.js:9:95740)
    at oS (framework-281bd828f4ecdac7.js:9:94295)
    at x (framework-281bd828f4ecdac7.js:33:1373)
K @ main-b471d74b2885b119.js:1
fn @ main-b471d74b2885b119.js:1
componentDidCatch @ main-b471d74b2885b119.js:1
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
main-b471d74b2885b119.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
K @ main-b471d74b2885b119.js:1
fn @ main-b471d74b2885b119.js:1
componentDidCatch @ main-b471d74b2885b119.js:1
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
framework-281bd828f4ecdac7.js:9 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20data%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lJ (framework-281bd828f4ecdac7.js:9:54221)
    at o (framework-281bd828f4ecdac7.js:9:59251)
    at uu (framework-281bd828f4ecdac7.js:9:71132)
    at i (framework-281bd828f4ecdac7.js:9:121294)
    at oO (framework-281bd828f4ecdac7.js:9:99114)
    at framework-281bd828f4ecdac7.js:9:98981
    at oF (framework-281bd828f4ecdac7.js:9:98988)
    at ox (framework-281bd828f4ecdac7.js:9:95740)
    at oS (framework-281bd828f4ecdac7.js:9:94295)
    at x (framework-281bd828f4ecdac7.js:33:1373)
a6 @ framework-281bd828f4ecdac7.js:9
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
main-b471d74b2885b119.js:1 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20data%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lJ (framework-281bd828f4ecdac7.js:9:54221)
    at o (framework-281bd828f4ecdac7.js:9:59251)
    at uu (framework-281bd828f4ecdac7.js:9:71132)
    at i (framework-281bd828f4ecdac7.js:9:121294)
    at oO (framework-281bd828f4ecdac7.js:9:99114)
    at framework-281bd828f4ecdac7.js:9:98981
    at oF (framework-281bd828f4ecdac7.js:9:98988)
    at ox (framework-281bd828f4ecdac7.js:9:95740)
    at oS (framework-281bd828f4ecdac7.js:9:94295)
    at x (framework-281bd828f4ecdac7.js:33:1373)
K @ main-b471d74b2885b119.js:1
fn @ main-b471d74b2885b119.js:1
componentDidCatch @ main-b471d74b2885b119.js:1
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
main-b471d74b2885b119.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
K @ main-b471d74b2885b119.js:1
fn @ main-b471d74b2885b119.js:1
componentDidCatch @ main-b471d74b2885b119.js:1
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
main-b471d74b2885b119.js:1 Error rendering page:  Error: Cancel rendering route
    at c (main-b471d74b2885b119.js:1:12323)
    at main-b471d74b2885b119.js:1:12275
    at new Promise (<anonymous>)
    at eo (main-b471d74b2885b119.js:1:12252)
    at main-b471d74b2885b119.js:1:10863
(anonymous) @ main-b471d74b2885b119.js:1
Promise.catch (async)
fn @ main-b471d74b2885b119.js:1
componentDidCatch @ main-b471d74b2885b119.js:1
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
main-b471d74b2885b119.js:1 Error rendering page:  Error: Cancel rendering route
    at c (main-b471d74b2885b119.js:1:12323)
    at main-b471d74b2885b119.js:1:12275
    at new Promise (<anonymous>)
    at eo (main-b471d74b2885b119.js:1:12252)
    at main-b471d74b2885b119.js:1:10863
(anonymous) @ main-b471d74b2885b119.js:1
Promise.catch (async)
fn @ main-b471d74b2885b119.js:1
componentDidCatch @ main-b471d74b2885b119.js:1
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
main-b471d74b2885b119.js:1 Error rendering page:  Error: Cancel rendering route
    at c (main-b471d74b2885b119.js:1:12323)
    at main-b471d74b2885b119.js:1:12275
    at new Promise (<anonymous>)
    at eo (main-b471d74b2885b119.js:1:12252)
    at main-b471d74b2885b119.js:1:10863
(anonymous) @ main-b471d74b2885b119.js:1
Promise.catch (async)
fn @ main-b471d74b2885b119.js:1
componentDidCatch @ main-b471d74b2885b119.js:1
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
main-b471d74b2885b119.js:1 Error rendering page:  Error: Cancel rendering route
    at c (main-b471d74b2885b119.js:1:12323)
    at main-b471d74b2885b119.js:1:12275
    at new Promise (<anonymous>)
    at eo (main-b471d74b2885b119.js:1:12252)
    at main-b471d74b2885b119.js:1:10863
(anonymous) @ main-b471d74b2885b119.js:1
Promise.catch (async)
fn @ main-b471d74b2885b119.js:1
componentDidCatch @ main-b471d74b2885b119.js:1
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33
main-b471d74b2885b119.js:1 Error rendering page:  Error: Cancel rendering route
    at c (main-b471d74b2885b119.js:1:12323)
    at main-b471d74b2885b119.js:1:12275
    at new Promise (<anonymous>)
    at eo (main-b471d74b2885b119.js:1:12252)
    at main-b471d74b2885b119.js:1:10863
(anonymous) @ main-b471d74b2885b119.js:1
Promise.catch (async)
fn @ main-b471d74b2885b119.js:1
componentDidCatch @ main-b471d74b2885b119.js:1
a.componentDidCatch.t.callback @ framework-281bd828f4ecdac7.js:9
lH @ framework-281bd828f4ecdac7.js:9
uY @ framework-281bd828f4ecdac7.js:9
e @ framework-281bd828f4ecdac7.js:9
(anonymous) @ framework-281bd828f4ecdac7.js:9
oI @ framework-281bd828f4ecdac7.js:9
oS @ framework-281bd828f4ecdac7.js:9
x @ framework-281bd828f4ecdac7.js:33
T @ framework-281bd828f4ecdac7.js:33

    at i (framework-281bd828f4ecdac7.js:9:121294)
    at oO (framework-281bd828f4ecdac7.js:9:99114)
    at framework-281bd828f4ecdac7.js:9:98981
    at oF (framework-281bd828f4ecdac7.js:9:98988)
    at ox (framework-281bd828f4ecdac7.js:9:95740)
    at oS (framework-281bd828f4ecdac7.js:9:94295)
    at x (framework-281bd828f4ecdac7.js:33:1373)
a

### To reproduce

CREATE TABLE `booking` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(400) DEFAULT NULL,
  `ownerId` int(11) DEFAULT NULL,
  `eventstart` datetime DEFAULT NULL,
  `roomId` int(11) DEFAULT NULL,
  `eventend` datetime DEFAULT NULL,
  `allday` bit(1) DEFAULT NULL,
  `repBookId` int(11) DEFAULT NULL,
  `clientId` int(11) DEFAULT NULL,
  `invoiceId` int(11) DEFAULT NULL,
  `paidId` int(11) DEFAULT NULL,
  `mojp` bit(1) NOT NULL DEFAULT b'0',
  `paid` tinyint(1) DEFAULT NULL,
  `mpid` int(11) DEFAULT NULL,
  `mpclientId` int(11) DEFAULT NULL,
  `gcal` bit(1) NOT NULL DEFAULT b'0',
  `gcaluid` varchar(200) DEFAULT NULL,
  `mpType` varchar(10) DEFAULT NULL,
  `online` bit(1) DEFAULT b'0',
  `proformaInvoiceId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `eventstart` (`eventstart`),
  KEY `FK_bookingrepeatb` (`repBookId`),
  KEY `FK_booking` (`roomId`),
  KEY `FK_bookingusers` (`ownerId`),
  KEY `invoiceId` (`invoiceId`),
  KEY `paidId` (`paidId`),
  KEY `booking_ibfk_1` (`clientId`),
  KEY `FK_proformainvoice` (`proformaInvoiceId`),
  CONSTRAINT `FK_booking` FOREIGN KEY (`roomId`) REFERENCES `room` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_bookingrepeatb` FOREIGN KEY (`repBookId`) REFERENCES `repeatbookings` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_bookingusers` FOREIGN KEY (`ownerId`) REFERENCES `user` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_proformainvoice` FOREIGN KEY (`proformaInvoiceId`) REFERENCES `proformainvoice` (`id`) ON DELETE SET NULL,
  CONSTRAINT `booking_ibfk_1` FOREIGN KEY (`clientId`) REFERENCES `client` (`id`) ON DELETE SET NULL,
  CONSTRAINT `booking_ibfk_2` FOREIGN KEY (`invoiceId`) REFERENCES `invoice` (`id`) ON DELETE SET NULL,
  CONSTRAINT `booking_ibfk_3` FOREIGN KEY (`paidId`) REFERENCES `payment` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=74996 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_slovenian_ci CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

the constraints and indexes probably don't matter in this case...

**Comment by tianzhou** [comment]
![CleanShot 2023-12-17 at 22-53-32 png](https://github.com/sqlchat/sqlchat/assets/230323/76cd7687-3079-40e6-914c-e9319250f9f5)

![CleanShot 2023-12-17 at 22-53-46 png](https://github.com/sqlchat/sqlchat/assets/230323/2a0ea8ea-90b6-4c33-934b-c3c32d9716fa)


Unable to reproduce with the schema (without those constraints)
