### ISSUE TITLE
add button to update database of connection manually

### ISSUE THREAD

**Issue by CorrectRoadH** [sqlchat/sqlchat#57]
### Is your feature request related to a problem?

When I add some databases to the database👀 the database of Select didn't update. Regardless I to change the connection or relaunch the browser, the config didn't refetch. Unless changing the config of the connection. 
So I think adding a button to update the database is a good idea.

### Describe the solution you'd like

add a button to refetch the database of connection.

**Comment by tianzhou** [comment]
We now have a sync button to sync the schema
