### ISSUE TITLE
Support GPT 4.0

### ISSUE THREAD

**Issue by zhangbinhui** [sqlchat/sqlchat#60]
### Is your feature request related to a problem?

目前用的是 gpt3.5 吧？如果我想改成 4，在哪里可以更改？

### Describe the solution you'd like

界面添加也行，或者配置文件在哪，谢谢。

**Comment by dolphinsboy** [comment]
https://github.com/sqlchat/sqlchat/blob/a82308bd8b8fd4efb77f19f167419d1bc635aa45/src/pages/api/chat.ts#L27

```
body: JSON.stringify({
      model: "gpt-3.5-turbo",
      messages: reqBody.messages,
      temperature: 0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
      stream: true,
    }),
  });
```

代码里面写死了的，可改代码或者env定义改

**Comment by zhangbinhui** [comment]
> 

谢谢，看起来只能改代码，再自己重新打包？用docker改env 好像只能修改.env里已经有的参数，这个model并不在.env里面，我就不会弄了。。。

**Comment by tianzhou** [comment]
It's released
