### ISSUE TITLE
我希望sqlchat能增加两个新特性，可以大大提升用户体验 (I hope that SQLChat can add two new features, which can greatly enhance the user experience.)

### ISSUE THREAD

**Issue by zhangbinhui** [sqlchat/sqlchat#66]
### Is your feature request related to a problem?

我每次问它问题，它都要反问我你的数据库模式是啥？表名是啥？重复的问题很浪费时间。
Every time I ask it a question, it always asks me back what my database schema is and what the table name is. It's very time-consuming to deal with repetitive questions like that.

### Describe the solution you'd like

一是可以自定义保存多个提示词，类似现在很多chatgpt web项目那样，因为现在gpt3.5是没有记忆的，我每次问问题，它都要反问我你的数据库模式是啥？表名是啥？我想在提示词里固化这些信息。这样会方便很多。
One is the ability to customize and save multiple prompts, similar to many chatbot web projects nowadays. Because GPT3.5 currently has no memory, every time I ask a question it asks me back about my database schema and table names. I want to solidify this information in the prompts so that it will be more convenient.

二是，跳过手工点执行那步，生成完信息直接执行，我可以在执行结果之后再做调整，手动点一下执行没意义。然后执行结果可以提供导出csv，感谢。
The second point is to skip the manual execution step and directly execute after generating the information. I can make adjustments after seeing the execution results, so manually clicking on execution is meaningless. Then, the execution results can be exported as a CSV file. Thank you.

**Comment by CorrectRoadH** [comment]
🤣 你想要的功能感觉像这个 #44 #52

**Comment by zhangbinhui** [comment]
> 🤣 你想要的功能感觉像这个 #44 #52

大佬好，看了你的issue，确实类似，你给的方案也可以，我只是一个使用者，从自己的角度出发提的方案，让开发团队想办法解决吧，哈哈。

**Comment by evanlong0926** [comment]
> 🤣 你想要的功能感觉像这个 #44 #52

我和#44这个问题观点一样的，应该展示结果。因为大部分的用户可能是不想看，比如我更关心结果🤣

**Comment by tianzhou** [comment]
Thanks to @CorrectRoadH . This is already released.
