### ISSUE TITLE
prompt optmization

### ISSUE THREAD

**Issue by yujun-8848** [sqlchat/sqlchat#77]
### Is your feature request related to a problem?

每当我在我的某一个数据库下面提问时，sqlchat都会带上该数据库的中数据表的schema信息，但是由于chatGPT有询问max_tokens限制，导致当该数据库下面表信息过多时，无法进行正确的提问。

### Describe the solution you'd like

是否可以进行某些优化来解决这一问题，比如将数据库进行更细粒度控制，在界面上可以勾选某一数据库下面的某一些表，然后再根据该一个或者多个表进行提问，这样prompt会显得更短

**Comment by tianzhou** [comment]
It's implemented
