### ISSUE TITLE
Returns 500 in the chat session after adding the database connection

### ISSUE THREAD

**Issue by blue-xu-blue** [sqlchat/sqlchat#9]
连接成功了数据库，但是进行对话报错500，打印reqBody.messages为空

**Comment by boojack** [comment]
@blue-xu-blue Thanks for your report. However, I cannot reproduce this in my environment. Could you please provide more detailed steps?

**Comment by boojack** [comment]
I think the main reason is that you cannot access the OpenAI API. And we have provided configuring the OpenAI API key and endpoint in the settings dialog. Please configure your OpenAI configuration and try it again. Feel free to reopen the issue if it still exists.

<img width="530" alt="image" src="https://user-images.githubusercontent.com/24653555/230548923-e1242ff8-849b-4d11-baba-bd2e9b3835cb.png">
